import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { lookup } from "node:dns/promises";

export const dynamic = "force-dynamic";

const TIMEOUT_MS = 10_000;
const PACE_MS = 450;

/**
 * CDN/WAF "edge block" signatures — mirrors checker-node/src/checker.js so this
 * live diagnostic classifies responses the same way the real checker nodes do.
 */
const CDN_BLOCK_SIGNATURES: { label: string; test: (body: string, headers: Headers) => boolean }[] = [
  {
    label: "CloudFront",
    test: (body, headers) =>
      (headers.get("x-cache")?.includes("Error from cloudfront") ?? false) && /request blocked/i.test(body),
  },
  {
    label: "CloudFront",
    test: (body) => /generated by cloudfront/i.test(body) && /could not be satisfied/i.test(body),
  },
  {
    label: "Cloudflare",
    test: (body) => /attention required[!]?\s*\|\s*cloudflare/i.test(body),
  },
  {
    label: "Cloudflare",
    test: (body) => /sorry, you have been blocked/i.test(body) && /cloudflare/i.test(body),
  },
];

function detectCdnBlock(body: string, headers: Headers): string | null {
  for (const signature of CDN_BLOCK_SIGNATURES) {
    if (signature.test(body, headers)) return signature.label;
  }
  return null;
}

function classifyError(err: unknown): string {
  if (!(err instanceof Error)) return "Unknown Error";
  if (err.name === "AbortError") return "Timeout";

  const code = (err.cause as { code?: string } | undefined)?.code ?? (err as { code?: string }).code;
  switch (code) {
    case "ENOTFOUND":
    case "EAI_AGAIN":
      return "DNS Error";
    case "ECONNREFUSED":
      return "Connection Refused";
    case "ECONNRESET":
      return "Connection Reset";
    case "CERT_HAS_EXPIRED":
    case "UNABLE_TO_VERIFY_LEAF_SIGNATURE":
    case "ERR_TLS_CERT_ALTNAME_INVALID":
    case "DEPTH_ZERO_SELF_SIGNED_CERT":
      return "SSL Error";
    default:
      return err.message || "Unknown Error";
  }
}

type LiveCheckEvent =
  | { type: "step"; message: string }
  | {
      type: "result";
      status: "up" | "down" | "blocked";
      statusCode: number | null;
      responseTimeMs: number | null;
      errorMessage: string | null;
      checkedAt: string;
    };

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * GET /api/domains/[id]/live-check
 *
 * Streams (via SSE) a real-time, step-by-step trace of a live reachability
 * check for one domain — DNS lookup, HTTP request, and response
 * classification — run from the main server, mirroring checker-node's logic.
 */
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await getSession();
  if (!session) {
    return new Response("Unauthorized", { status: 401 });
  }

  const { id } = await params;
  const domainId = Number(id);
  if (!Number.isFinite(domainId)) {
    return new Response("Not found", { status: 404 });
  }

  const domain = await prisma.domain.findUnique({ where: { id: domainId } });
  if (!domain) {
    return new Response("Not found", { status: 404 });
  }

  const encoder = new TextEncoder();
  let aborted = false;

  const stream = new ReadableStream({
    async start(controller) {
      const send = (event: LiveCheckEvent) => {
        if (aborted) return;
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(event)}\n\n`));
      };
      const finish = (event: LiveCheckEvent) => {
        send(event);
        controller.close();
      };

      let hostname: string;
      try {
        hostname = new URL(domain.url).hostname;
      } catch {
        finish({
          type: "result",
          status: "down",
          statusCode: null,
          responseTimeMs: null,
          errorMessage: "Invalid URL",
          checkedAt: new Date().toISOString(),
        });
        return;
      }

      send({ type: "step", message: `Target: ${domain.domain} -> ${domain.url}` });
      await sleep(PACE_MS);

      send({ type: "step", message: `Resolving DNS for ${hostname}...` });
      try {
        const dnsStart = Date.now();
        const { address, family } = await lookup(hostname);
        send({
          type: "step",
          message: `Resolved ${hostname} -> ${address} (IPv${family}) in ${Date.now() - dnsStart}ms`,
        });
      } catch (err) {
        const reason = classifyError(err);
        send({ type: "step", message: `DNS resolution failed: ${reason}` });
        finish({
          type: "result",
          status: "down",
          statusCode: null,
          responseTimeMs: null,
          errorMessage: reason,
          checkedAt: new Date().toISOString(),
        });
        return;
      }
      await sleep(PACE_MS);

      send({
        type: "step",
        message: `Sending GET ${domain.url} (redirect: manual, timeout ${TIMEOUT_MS / 1000}s, User-Agent: Mi-hawk-Checker/1.0)...`,
      });

      for (let attempt = 1; attempt <= 2; attempt++) {
        const abortController = new AbortController();
        const timer = setTimeout(() => abortController.abort(), TIMEOUT_MS);
        const startedAt = Date.now();

        try {
          const response = await fetch(domain.url, {
            method: "GET",
            redirect: "manual",
            signal: abortController.signal,
            headers: { "User-Agent": "Mi-hawk-Checker/1.0" },
          });
          const responseTimeMs = Date.now() - startedAt;

          send({
            type: "step",
            message: `Received HTTP ${response.status} ${response.statusText || ""} in ${responseTimeMs}ms`.trim(),
          });

          const server = response.headers.get("server");
          const cache = response.headers.get("x-cache") ?? response.headers.get("via");
          if (server || cache) {
            send({
              type: "step",
              message: `Headers - ${[server && `server: ${server}`, cache && `x-cache/via: ${cache}`]
                .filter(Boolean)
                .join(", ")}`,
            });
          }
          await sleep(PACE_MS);

          if (response.status >= 200 && response.status < 400) {
            send({ type: "step", message: `Status ${response.status} is within 200-399 -> REACHABLE` });
            finish({
              type: "result",
              status: "up",
              statusCode: response.status,
              responseTimeMs,
              errorMessage: null,
              checkedAt: new Date().toISOString(),
            });
            return;
          }

          send({
            type: "step",
            message: `Status ${response.status} is outside 200-399 - checking response body for CDN/WAF block-page signatures...`,
          });

          let cdnBlock: string | null = null;
          try {
            const body = await response.text();
            cdnBlock = detectCdnBlock(body, response.headers);
          } catch {
            // Body unreadable - fall through and report as "down".
          }
          await sleep(PACE_MS);

          if (cdnBlock) {
            send({ type: "step", message: `Matched ${cdnBlock} block-page signature -> BLOCKED (checker IP flagged)` });
            finish({
              type: "result",
              status: "blocked",
              statusCode: response.status,
              responseTimeMs,
              errorMessage: `Blocked by ${cdnBlock} (checker IP flagged - site may still be reachable for real visitors)`,
              checkedAt: new Date().toISOString(),
            });
          } else {
            send({ type: "step", message: `No CDN block signature matched -> DOWN` });
            finish({
              type: "result",
              status: "down",
              statusCode: response.status,
              responseTimeMs,
              errorMessage: `${response.status} ${response.statusText || "Error"}`.trim(),
              checkedAt: new Date().toISOString(),
            });
          }
          return;
        } catch (err) {
          if (err instanceof Error && err.name === "AbortError" && attempt === 1) {
            send({ type: "step", message: `Request timed out after ${TIMEOUT_MS / 1000}s - retrying once...` });
            continue;
          }

          const reason = classifyError(err);
          send({ type: "step", message: `Request failed: ${reason}` });
          finish({
            type: "result",
            status: "down",
            statusCode: null,
            responseTimeMs: null,
            errorMessage: reason,
            checkedAt: new Date().toISOString(),
          });
          return;
        } finally {
          clearTimeout(timer);
        }
      }
    },
    cancel() {
      aborted = true;
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}
