import { config } from "./config.js";

/**
 * Signatures for CDN/WAF "edge block" pages — generated by the CDN itself
 * (never reaching the site's origin) when it flags the *checker's* IP, not
 * the site. These are reported as "blocked" rather than "down" since real
 * visitors from a different IP may still reach the site fine.
 */
const CDN_BLOCK_SIGNATURES = [
  {
    label: "CloudFront",
    test: (body, headers) =>
      (headers.get("x-cache")?.includes("Error from cloudfront") ?? false) &&
      /request blocked/i.test(body),
  },
  {
    label: "CloudFront",
    test: (body) => /generated by cloudfront/i.test(body) && /could not be satisfied/i.test(body),
  },
  {
    label: "Cloudflare",
    test: (body) => /attention required[!]?\s*\|\s*cloudflare/i.test(body),
  },
  {
    label: "Cloudflare",
    test: (body) => /sorry, you have been blocked/i.test(body) && /cloudflare/i.test(body),
  },
];

/** Checks a non-2xx response body/headers against known CDN edge-block signatures. */
function detectCdnBlock(body, headers) {
  for (const signature of CDN_BLOCK_SIGNATURES) {
    if (signature.test(body, headers)) return signature.label;
  }
  return null;
}

/**
 * Matches an HTML `<meta http-equiv="refresh" content="N;url=...">` tag —
 * the "click gate" / bridge-page pattern used by some domains to land on a
 * 200 OK page that auto-redirects to the real destination after a delay.
 */
const META_REFRESH_PATTERN = /<meta[^>]+http-equiv\s*=\s*["']?refresh["']?[^>]*content\s*=\s*["']?\s*\d+\s*;\s*url\s*=\s*['"]?([^'">\s]+)/i;

/** Resolves a meta-refresh target to an absolute URL, or null if none/unparseable. */
function detectMetaRefresh(body, baseUrl) {
  const match = body.match(META_REFRESH_PATTERN);
  if (!match) return null;
  try {
    return new URL(match[1], baseUrl).toString();
  } catch {
    return null;
  }
}

/**
 * Checks a single domain over HTTP(S).
 *
 * Redirects are NOT followed: a 3xx response means the domain's own server
 * answered, which counts as UP regardless of where it points (the redirect
 * target, if also monitored, is checked as its own domain). Status codes
 * 200-399 are treated as UP. A 200 OK HTML response is also scanned for a
 * meta-refresh "bridge"/click-gate page (see {@link detectMetaRefresh}) -
 * its target is reported the same way as a 3xx Location. A non-2xx response
 * matching a known CDN/WAF edge-block page (see {@link detectCdnBlock}) is
 * treated as BLOCKED.
 * Anything else (4xx, 5xx, DNS failure, connection refused, TLS errors, ...)
 * is treated as DOWN with a human-readable error message.
 *
 * A request that times out is retried once with a fresh timeout before being
 * reported as DOWN — some sites occasionally respond just past the timeout
 * window, and a single slow response shouldn't flip a domain's status (this
 * matters most for "global", which has only one checkpoint, so one timeout
 * there makes that region's score swing from 100% to 0%).
 */
export async function checkDomain(domain) {
  for (let attempt = 1; attempt <= 2; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), config.timeoutMs);
    const startedAt = Date.now();

    try {
      const response = await fetch(domain.url, {
        method: "GET",
        redirect: "manual",
        signal: controller.signal,
        headers: { "User-Agent": "Mi-hawk-Checker/1.0" },
      });
      const responseTimeMs = Date.now() - startedAt;

      if (response.status >= 200 && response.status < 400) {
        let redirectUrl = null;
        if (response.status >= 300) {
          const location = response.headers.get("location");
          if (location) {
            try {
              redirectUrl = new URL(location, domain.url).toString();
            } catch {
              // Malformed Location header - leave redirectUrl null, still report "up".
            }
          }
        } else if (response.headers.get("content-type")?.includes("text/html")) {
          try {
            const body = await response.text();
            redirectUrl = detectMetaRefresh(body, domain.url);
          } catch {
            // Body unreadable - leave redirectUrl null, still report "up".
          }
        }

        return {
          domainId: domain.id,
          status: "up",
          statusCode: response.status,
          responseTimeMs,
          redirectUrl,
          errorMessage: null,
          checkedAt: new Date().toISOString(),
        };
      }

      let cdnBlock = null;
      try {
        const body = await response.text();
        cdnBlock = detectCdnBlock(body, response.headers);
      } catch {
        // Body unreadable (e.g. aborted) - fall through and report as "down".
      }

      if (cdnBlock) {
        return {
          domainId: domain.id,
          status: "blocked",
          statusCode: response.status,
          responseTimeMs,
          errorMessage: `Blocked by ${cdnBlock} (checker IP flagged - site may still be reachable for real visitors)`,
          checkedAt: new Date().toISOString(),
        };
      }

      return {
        domainId: domain.id,
        status: "down",
        statusCode: response.status,
        responseTimeMs,
        errorMessage: `${response.status} ${response.statusText || "Error"}`.trim(),
        checkedAt: new Date().toISOString(),
      };
    } catch (err) {
      if (err.name === "AbortError" && attempt === 1) continue;

      return {
        domainId: domain.id,
        status: "down",
        statusCode: null,
        responseTimeMs: null,
        errorMessage: classifyError(err),
        checkedAt: new Date().toISOString(),
      };
    } finally {
      clearTimeout(timer);
    }
  }
}

function classifyError(err) {
  if (err.name === "AbortError") return "Timeout";

  const code = err.cause?.code ?? err.code;
  switch (code) {
    case "ENOTFOUND":
    case "EAI_AGAIN":
      return "DNS Error";
    case "ECONNREFUSED":
      return "Connection Refused";
    case "ECONNRESET":
      return "Connection Reset";
    case "CERT_HAS_EXPIRED":
    case "UNABLE_TO_VERIFY_LEAF_SIGNATURE":
    case "ERR_TLS_CERT_ALTNAME_INVALID":
    case "DEPTH_ZERO_SELF_SIGNED_CERT":
      return "SSL Error";
    default:
      return err.message || "Unknown Error";
  }
}
